/**
 * Emits `lib/sdk/CLAUDE.md` — a generated reference documenting the SDK
 * for Claude Code (and humans) working in the consuming project.
 *
 * Audience priority:
 *   1. Claude Code agents working in the user's frontend project — they
 *      need a compact, scannable reference of available functions and
 *      idiomatic usage patterns.
 *   2. Agency devs reading occasionally — they want a starting point and
 *      a regen reminder.
 *
 * Detailed per-property schema documentation lives in the sibling
 * `types.ts` file (which Claude Code can read on demand). This file
 * stays high-level: a function table + canonical example + patterns.
 */

import type { Manifest } from "../types/manifest.js";
import type { AbilityNameMap } from "../commands/generate.js";

export function renderClaudeMdFile(
  manifest: Manifest,
  abilityNames: AbilityNameMap[],
): string {
  const rows = abilityNames.map((a) => renderTableRow(a, manifest));
  const acfDetails = abilityNames
    .map((a) => renderAcfDetails(a, manifest))
    .filter((s): s is string => s !== null);

  return `# wp-headless-kit — Generated SDK Reference

> **AUTOGENERATED.** Do not edit by hand. Regenerate with \`wpheadless sync <project-dir>\`.
>
> Source: ${manifest.source} · Manifest v${manifest.schemaVersion} · Fetched ${manifest.fetchedAt} · ${manifest.abilities.length} abilities

## What this is

This project consumes a WordPress install exposing the official MCP Adapter (\`wordpress/mcp-adapter\`) through a typed SDK auto-generated from the live ability schemas. You don't call WP REST endpoints directly — you call typed functions like \`getBeers(client)\` and get back fully-typed data, including ACF fields when the WP-side post type has any.

## How to use the SDK

\`\`\`ts
// Server Component — credentials never reach the browser.
import { getBeers } from "@/lib/sdk";
import { skmClient } from "@/lib/skm/client";

export const revalidate = 60; // ISR

export default async function BeersPage() {
  const { beers } = await getBeers(skmClient);
  //      ^^^^^ fully typed, including \`acf\` when the post type has fields
  return /* render beers */;
}
\`\`\`

The client (\`skmClient\`) is server-only — it carries WP credentials and is gated by \`import "server-only"\`. Importing it from a Client Component fails at build time. For client-side data needs, build a route handler that calls the SDK server-side and returns the data through \`fetch\`.

## Available abilities

| Function | Input | Returns | ACF |
| --- | --- | --- | --- |
${rows.join("\n")}

All input types are optional — every input field declared in the WP-side schemas has a \`default\`, so callers can pass \`{}\` (or, for parameterless abilities, omit the argument entirely).

The output types' wrapper key matches the ability's purpose (\`{ posts: [...] }\`, \`{ beers: [...] }\`, \`{ menus: [...] }\`). Per-item shape is \`{ id, title, excerpt, date, slug, link${acfDetails.length > 0 ? ", acf" : ""} }\` for CPT-list abilities; menu items have a different shape (id, title, url, target, object_type, object_id, parent_id, order). See \`./types.ts\` for the full property-by-property schemas.${acfDetails.length > 0 ? `

## ACF fields per ability

${acfDetails.join("\n\n")}` : ""}

## Patterns

### ISR (Incremental Static Regeneration)
Each Server Component opts into per-route revalidation: \`export const revalidate = 60\`. Default is no revalidation. Tune per-route based on how stale the data can be.

### Error handling
The client throws \`SkmClientError\` (exported from \`./client\`) on transport, protocol, or ability failures. In Server Components, let them bubble — Next.js's error boundary catches them. In route handlers, catch and return a typed error response.

### Where to put new files
- \`lib/sdk/\` is **regenerated**. Never edit files here by hand — \`wpheadless sync\` will overwrite them.
- \`lib/skm/\` is **hand-crafted glue** (the client wrapper, request helpers, opinionated patterns). Survives regenerations.

### Regenerating after WP-side schema changes
\`\`\`bash
wpheadless sync <project-dir>
\`\`\`
Refreshes \`.skm/manifest.json\` from the saved WP URL and rewrites all four SDK files. Run after any change to ability registration, ACF field groups, or post type registration on the WP side.

### Server-only imports
\`lib/skm/client.ts\` is gated by \`import "server-only"\`. Always call SDK functions from Server Components, route handlers, or server actions — never from Client Components. If you need data on the client, fetch it through a route handler that wraps the SDK call.

### Strangler-fig migration (incremental headless)
\`app/[[...slug]]/route.ts\` is a catch-all handler that proxies any unmatched route to \`process.env.WP_PROXY_URL\`. Workflow:

1. Set \`WP_PROXY_URL\` in \`.env.local\` to the original WordPress site URL.
2. Run \`pnpm dev\`. Every route falls through to the original site — visually identical to before.
3. Build a Next.js page for one route at a time (e.g. \`app/posts/page.tsx\`). Explicit local routes always win, so anything you implement immediately replaces the proxied version. Anything you haven't implemented stays proxied.
4. Repeat. Decommission the original site when no routes are still proxying through.

This is the agency-friendly migration story: clients keep their current site working at every commit; you replace pieces on your own schedule.

To opt out, leave \`WP_PROXY_URL\` empty (the handler returns 404), or delete \`app/[[...slug]]/route.ts\` entirely.

When pointing at a local-dev host (\`*.local\`, \`*.test\`) with a self-signed cert, also set \`NODE_TLS_REJECT_UNAUTHORIZED=0\` in \`.env.local\` so Node's fetch accepts the cert. Dev-only — never in production.

## Out of scope (deliberately)

This SDK does not currently emit:
- Form submission, search, preview-mode wiring, multilingual support, WooCommerce. These were explicitly deferred per the project's \`CLAUDE.md\`.
`;
}

function renderTableRow(a: AbilityNameMap, manifest: Manifest): string {
  const ability = manifest.abilities.find((x) => x.name === a.abilityName);
  const hasAcf = abilityHasAcf(ability);
  // Three signature shapes: no input, optional input, required input. The
  // `?` suffix on Input/input mirrors the actual TS signature so a reader
  // scanning the table can map call sites to types without opening the SDK.
  const inputCol = a.hasNoInput
    ? "—"
    : a.hasRequiredInput
      ? `\`${a.pascal}Input\``
      : `\`${a.pascal}Input?\``;
  const signature = a.hasNoInput
    ? `\`${a.camel}(client)\``
    : a.hasRequiredInput
      ? `\`${a.camel}(client, input)\``
      : `\`${a.camel}(client, input?)\``;
  return `| ${signature} | ${inputCol} | \`${a.pascal}Output\` | ${hasAcf ? "yes" : "no"} |`;
}

function renderAcfDetails(a: AbilityNameMap, manifest: Manifest): string | null {
  const ability = manifest.abilities.find((x) => x.name === a.abilityName);
  if (!ability) return null;
  const acfFields = extractAcfFields(ability);
  if (acfFields.length === 0) return null;

  const lines = acfFields.map(
    ({ name, summary }) => `- \`${name}\`: ${summary}`,
  );
  return `### \`${a.camel}\` (${a.abilityName})

ACF fields populated when set on a post:
${lines.join("\n")}`;
}

function abilityHasAcf(ability: { outputSchema?: Record<string, unknown> } | undefined): boolean {
  return extractAcfSchema(ability) !== null;
}

interface AcfFieldSummary {
  name: string;
  summary: string;
}

function extractAcfFields(ability: {
  outputSchema?: Record<string, unknown>;
} | undefined): AcfFieldSummary[] {
  const acfSchema = extractAcfSchema(ability);
  if (!acfSchema) return [];
  const props = acfSchema.properties as Record<string, Record<string, unknown>> | undefined;
  if (!props) return [];

  return Object.entries(props).map(([name, spec]) => {
    return { name, summary: summarizeFieldSpec(spec) };
  });
}

function extractAcfSchema(
  ability: { outputSchema?: Record<string, unknown> } | undefined,
): Record<string, unknown> | null {
  if (!ability?.outputSchema) return null;
  const properties = ability.outputSchema.properties as Record<string, Record<string, unknown>> | undefined;
  if (!properties) return null;
  // CPT-list output schemas: properties.<wrapper_key>.items.properties.acf
  for (const value of Object.values(properties)) {
    const items = value.items as Record<string, unknown> | undefined;
    if (!items) continue;
    const itemProps = items.properties as Record<string, Record<string, unknown>> | undefined;
    if (!itemProps) continue;
    const acf = itemProps.acf;
    if (acf && typeof acf === "object") {
      return acf as Record<string, unknown>;
    }
  }
  return null;
}

function summarizeFieldSpec(spec: Record<string, unknown>): string {
  const typeLabel = describeShape(spec);
  const desc = typeof spec.description === "string" ? spec.description : "";
  return desc ? `${typeLabel} — ${desc}` : typeLabel;
}

/**
 * One-line shape description for a JSON Schema fragment.
 * For objects with known properties, lists the first few keys (e.g.
 * `{ name, role, photo }`) so repeaters/groups/images carry useful
 * information into CLAUDE.md without re-rendering the whole schema.
 *
 * Special-case: a `oneOf` whose variants each carry a const `acf_fc_layout`
 * is an ACF flexible_content discriminated union — render as the union of
 * layout names (`hero | text_block | card_grid`) which is what consumers
 * actually want to see.
 */
function describeShape(spec: Record<string, unknown>): string {
  if (Array.isArray(spec.oneOf)) {
    return describeOneOf(spec.oneOf as Array<Record<string, unknown>>);
  }
  const t = spec.type;
  const fmt = spec.format;
  if (Array.isArray(t)) return t.join(" | ");
  if (t === "array") {
    const items = spec.items as Record<string, unknown> | undefined;
    return `array<${items ? describeShape(items) : "unknown"}>`;
  }
  if (t === "object") return describeObjectKeys(spec);
  if (typeof t === "string") return fmt ? `${t} (${String(fmt)})` : t;
  return "unknown";
}

function describeOneOf(variants: Array<Record<string, unknown>>): string {
  const layoutNames = variants
    .map((v) => extractFcLayoutName(v))
    .filter((name): name is string => name !== null);
  if (layoutNames.length === variants.length && layoutNames.length > 0) {
    return layoutNames.join(" | ");
  }
  // Fall back to per-variant shape rendering for non-FC oneOf usages.
  return variants.map((v) => describeShape(v)).join(" | ");
}

function extractFcLayoutName(variant: Record<string, unknown>): string | null {
  const props = variant.properties as Record<string, unknown> | undefined;
  if (!props) return null;
  const layout = props.acf_fc_layout as Record<string, unknown> | undefined;
  if (!layout) return null;
  return typeof layout.const === "string" ? layout.const : null;
}

function describeObjectKeys(spec: Record<string, unknown>): string {
  const props = spec.properties as Record<string, unknown> | undefined;
  if (!props) return "object";
  const keys = Object.keys(props);
  if (keys.length === 0) return "object";
  const MAX = 4;
  if (keys.length <= MAX) return `{ ${keys.join(", ")} }`;
  return `{ ${keys.slice(0, MAX).join(", ")}, … }`;
}
