/**
 * Emits `lib/sdk/client.ts` — a portable MCP HTTP client for the user's
 * Next.js / Node project. Zero runtime dependencies (Node 20+ native fetch).
 *
 * Implements the same Streamable HTTP handshake as the CLI's own client:
 * `initialize` → capture `Mcp-Session-Id` → `notifications/initialized`
 * → tool calls. Each `createClient()` returns a fresh handshake-on-first-call
 * instance, so callers can build it once at module init and reuse it.
 */

import type { Manifest } from "../types/manifest.js";

export function renderClientFile(manifest: Manifest): string {
  return `/**
 * AUTOGENERATED. Do not edit by hand.
 *
 * Source:      ${manifest.source}
 * Fetched at:  ${manifest.fetchedAt}
 * Manifest v:  ${manifest.schemaVersion}
 *
 * Regenerate with: \`wpheadless generate <project-dir>\`
 */

/* eslint-disable */
/* tslint:disable */

const PROTOCOL_VERSION = "2025-06-18";
const CLIENT_NAME = "wpheadless-sdk";
const CLIENT_VERSION = "0.1.0";

const DEFAULT_NAMESPACE = ${JSON.stringify(manifest.server.namespace)};
const DEFAULT_SERVER_ROUTE = ${JSON.stringify(manifest.server.route)};

export interface SkmClientOptions {
  /** Full WP site URL, e.g. "https://example.com". No trailing slash required. */
  wpUrl: string;
  /** WordPress username. */
  user: string;
  /** WordPress Application Password. */
  password: string;
  /** Optional override of the MCP server REST namespace. */
  namespace?: string;
  /** Optional override of the MCP server REST route. */
  serverRoute?: string;
}

export interface SkmClient {
  /** Call any ability by full name (e.g. "skm/get-posts"). Strongly typed wrappers in abilities.ts are preferred. */
  callAbility<TInput extends Record<string, unknown>, TOutput>(
    abilityName: string,
    input?: TInput,
  ): Promise<TOutput>;
}

export class SkmClientError extends Error {
  constructor(
    message: string,
    public readonly cause?: unknown,
    public readonly code?: number,
  ) {
    super(message);
    this.name = "SkmClientError";
  }
}

interface JsonRpcResponse<T> {
  jsonrpc: "2.0";
  id: number;
  result?: T;
  error?: { code: number; message: string; data?: unknown };
}

interface ToolCallResult<T> {
  content: Array<{ type: "text"; text: string }>;
  structuredContent?: { success: boolean; data: T; error?: string };
  isError: boolean;
}

/**
 * Build a strongly-typed-ish MCP client for the headless WP install.
 * Pair with the typed wrappers in abilities.ts for compile-time guarantees.
 */
export function createClient(opts: SkmClientOptions): SkmClient {
  const namespace = opts.namespace ?? DEFAULT_NAMESPACE;
  const serverRoute = opts.serverRoute ?? DEFAULT_SERVER_ROUTE;
  const baseUrl = opts.wpUrl.replace(/\\/+$/, "");
  const endpoint = \`\${baseUrl}/wp-json/\${namespace}/\${serverRoute}\`;
  const authHeader = \`Basic \${Buffer.from(\`\${opts.user}:\${opts.password}\`).toString("base64")}\`;

  let nextId = 1;
  let sessionId: string | null = null;
  let initialized = false;

  async function post(body: string, includeSession: boolean): Promise<Response> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      Accept: "application/json, text/event-stream",
      Authorization: authHeader,
    };
    if (includeSession && sessionId) {
      headers["Mcp-Session-Id"] = sessionId;
    }
    try {
      return await fetch(endpoint, { method: "POST", headers, body });
    } catch (err) {
      const cause = (err as { cause?: { code?: string } }).cause;
      if (
        cause?.code === "DEPTH_ZERO_SELF_SIGNED_CERT" ||
        cause?.code === "SELF_SIGNED_CERT_IN_CHAIN"
      ) {
        throw new SkmClientError(
          \`TLS error connecting to \${endpoint}. Local dev with a self-signed cert? Set NODE_TLS_REJECT_UNAUTHORIZED=0 (dev only — never in CI/prod).\`,
          err,
        );
      }
      throw new SkmClientError(\`Network error calling \${endpoint}: \${(err as Error).message}\`, err);
    }
  }

  async function parseRpcBody<T>(response: Response): Promise<JsonRpcResponse<T>> {
    const ct = response.headers.get("content-type")?.toLowerCase() ?? "";
    const text = await response.text();
    const json = ct.includes("text/event-stream") ? extractFirstSseDataLine(text) : text;
    if (!json) throw new SkmClientError(\`Empty response body (Content-Type: \${ct || "unknown"})\`);
    try {
      return JSON.parse(json) as JsonRpcResponse<T>;
    } catch (err) {
      throw new SkmClientError(\`Non-JSON response body (Content-Type: \${ct || "unknown"})\`, err);
    }
  }

  async function rpc<T>(method: string, params: Record<string, unknown> = {}): Promise<T> {
    const id = nextId++;
    const response = await post(JSON.stringify({ jsonrpc: "2.0", id, method, params }), true);
    if (!response.ok) {
      const text = await safeReadText(response);
      throw new SkmClientError(\`HTTP \${response.status}\${text ? \`: \${text}\` : ""}\`, undefined, response.status);
    }
    const payload = await parseRpcBody<T>(response);
    if (payload.error) {
      throw new SkmClientError(\`JSON-RPC error \${payload.error.code}: \${payload.error.message}\`, payload.error.data, payload.error.code);
    }
    if (payload.result === undefined) {
      throw new SkmClientError("JSON-RPC response missing both result and error fields");
    }
    return payload.result;
  }

  async function ensureInitialized(): Promise<void> {
    if (initialized) return;
    const initId = nextId++;
    const initBody = JSON.stringify({
      jsonrpc: "2.0",
      id: initId,
      method: "initialize",
      params: {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: {},
        clientInfo: { name: CLIENT_NAME, version: CLIENT_VERSION },
      },
    });
    const response = await post(initBody, false);
    sessionId = response.headers.get("mcp-session-id");
    if (!sessionId) {
      throw new SkmClientError("Server did not return Mcp-Session-Id header on initialize.");
    }
    if (!response.ok) {
      const text = await safeReadText(response);
      throw new SkmClientError(\`initialize failed: HTTP \${response.status}\${text ? \`: \${text}\` : ""}\`, undefined, response.status);
    }
    const payload = await parseRpcBody<unknown>(response);
    if (payload.error) {
      throw new SkmClientError(\`initialize JSON-RPC error \${payload.error.code}: \${payload.error.message}\`);
    }
    const notifyResponse = await post(
      JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }),
      true,
    );
    if (!notifyResponse.ok && notifyResponse.status !== 202) {
      const text = await safeReadText(notifyResponse);
      throw new SkmClientError(\`notifications/initialized failed: HTTP \${notifyResponse.status}\${text ? \`: \${text}\` : ""}\`);
    }
    await notifyResponse.text().catch(() => undefined);
    initialized = true;
  }

  return {
    async callAbility<TInput extends Record<string, unknown>, TOutput>(
      abilityName: string,
      input?: TInput,
    ): Promise<TOutput> {
      await ensureInitialized();
      const result = await rpc<ToolCallResult<TOutput>>("tools/call", {
        name: "mcp-adapter-execute-ability",
        arguments: {
          ability_name: abilityName,
          parameters: input ?? {},
        },
      });
      if (result.isError) {
        const text = result.content?.[0]?.text ?? "(no error text)";
        throw new SkmClientError(\`Ability \${abilityName} failed: \${text}\`);
      }
      const wrapped = result.structuredContent;
      if (!wrapped) {
        throw new SkmClientError(\`Ability \${abilityName} returned no structuredContent\`);
      }
      if (!wrapped.success) {
        throw new SkmClientError(\`Ability \${abilityName} reported failure: \${wrapped.error ?? "(no error)"}\`);
      }
      return wrapped.data;
    },
  };
}

function extractFirstSseDataLine(text: string): string | null {
  for (const line of text.split(/\\r?\\n/)) {
    if (line.startsWith("data:")) return line.slice(5).trim();
  }
  return null;
}

async function safeReadText(response: Response): Promise<string> {
  try {
    const text = await response.text();
    return text.length > 500 ? \`\${text.slice(0, 500)}…\` : text;
  } catch {
    return "";
  }
}
`;
}
