/**
 * `emitSdk` — pure-function SDK file emission.
 *
 * Takes a manifest, returns a `Map<filename, content>` — does NOT write
 * anywhere. Callers (CLI's runGenerate, SaaS worker's repo-write step) iterate
 * the map and persist the entries to the appropriate location.
 *
 * Output structure (relative paths within the project's `lib/sdk/` dir):
 *   - "types.ts"      — `<PascalName>Input` and `<PascalName>Output` per ability
 *   - "client.ts"     — portable MCP HTTP client (zero runtime deps)
 *   - "abilities.ts"  — one typed function per ability
 *   - "index.ts"      — barrel
 *   - "CLAUDE.md"     — human/Claude reference doc
 *
 * Per-ability progress is reported via the optional onProgress callback.
 */

import { compile, type JSONSchema } from "json-schema-to-typescript";
import { renderClientFile } from "./emit/client.js";
import { renderAbilitiesFile } from "./emit/abilities.js";
import { renderIndexFile } from "./emit/index_barrel.js";
import { renderClaudeMdFile } from "./emit/claude_md.js";
import {
  type AbilityNameMap,
  abilityNameToPascal,
  makeAbilityNames,
} from "./ability-names.js";
import type {
  AbilityManifestEntry,
  Manifest,
} from "./types/manifest.js";

export interface EmitSdkOptions {
  /** Optional progress callback fired once per ability as types are compiled. */
  onProgress?: (event: EmitProgress) => void;
}

export type EmitProgress = {
  kind: "ability";
  name: string;
  index: number;
  total: number;
};

/**
 * Compile the typed SDK from a manifest. Returns a map keyed by filename
 * (e.g. "types.ts", "client.ts", "CLAUDE.md") to UTF-8 file contents.
 *
 * Filenames are paths within the conventional `lib/sdk/` directory — callers
 * resolve them against their target location:
 *   const files = await emitSdk(manifest);
 *   for (const [name, contents] of files) {
 *     await writeFile(path.join(targetDir, name), contents);
 *   }
 */
export async function emitSdk(
  manifest: Manifest,
  opts: EmitSdkOptions = {},
): Promise<Map<string, string>> {
  const sections: string[] = [];
  const abilityNames: AbilityNameMap[] = [];

  for (let i = 0; i < manifest.abilities.length; i++) {
    const ability = manifest.abilities[i]!;
    opts.onProgress?.({
      kind: "ability",
      name: ability.name,
      index: i,
      total: manifest.abilities.length,
    });

    const block = await compileAbility(ability);
    sections.push(block);
    abilityNames.push(makeAbilityNames(ability));
  }

  const files = new Map<string, string>();
  files.set("types.ts", renderTypesFile(manifest, sections));
  files.set("client.ts", renderClientFile(manifest));
  files.set("abilities.ts", renderAbilitiesFile(manifest, abilityNames));
  files.set("index.ts", renderIndexFile());
  files.set("CLAUDE.md", renderClaudeMdFile(manifest, abilityNames));
  return files;
}

async function compileAbility(ability: AbilityManifestEntry): Promise<string> {
  const pascal = abilityNameToPascal(ability.name);
  const inputName = `${pascal}Input`;
  const outputName = `${pascal}Output`;

  const blocks: string[] = [
    `// ${ability.name} — ${ability.label}`,
  ];

  blocks.push(
    await compileSchema(ability.inputSchema, inputName, ability.description),
  );

  if (ability.outputSchema) {
    blocks.push(await compileSchema(ability.outputSchema, outputName));
  }

  return blocks.join("\n");
}

async function compileSchema(
  schema: Record<string, unknown>,
  name: string,
  description?: string,
): Promise<string> {
  // Per-call bannerComment is suppressed; we add a single file-level header instead.
  const compiled = await compile(schema as JSONSchema, name, {
    bannerComment: "",
    additionalProperties: false,
    style: { semi: true, singleQuote: false },
  });
  if (description) {
    return `/** ${description} */\n${compiled.trim()}\n`;
  }
  return `${compiled.trim()}\n`;
}

function renderStaticBlockTypes(): string {
  return `export interface BlockNode {
  blockName: string | null;
  attrs: Record<string, unknown>;
  innerBlocks?: BlockNode[];
  innerHTML?: string;
  innerContent?: Array<string | null>;
}
`;
}

function renderTypesFile(manifest: Manifest, sections: string[]): string {
  const header = [
    "/**",
    " * AUTOGENERATED. Do not edit by hand.",
    " *",
    " * Source:      " + manifest.source,
    " * Fetched at:  " + manifest.fetchedAt,
    " * Manifest v:  " + manifest.schemaVersion,
    " * Abilities:   " + manifest.abilities.length,
    " *",
    " * Regenerate with: `jab generate <project-dir>`",
    " */",
    "",
    "/* eslint-disable */",
    "/* tslint:disable */",
    "",
  ].join("\n");
  return header + renderStaticBlockTypes() + "\n" + sections.join("\n") + "\n";
}
