/**
 * Emits `lib/sdk/abilities.ts` — one strongly-typed function per ability,
 * each delegating to a JabClient passed at call time.
 *
 * Shape:
 *   import { createClient } from "./client";
 *   const jab = createClient({ wpUrl: ..., user: ..., password: ... });
 *   const { posts } = await getPosts(jab, { numberposts: 5 });
 *
 * Passing the client explicitly (rather than a singleton) keeps the SDK
 * usable from Server Components, API routes, scripts, and tests without
 * stateful module-level setup. The user can wrap with their own helper
 * if they want a singleton style.
 */

import type { Manifest } from "../types/manifest.js";
import type { AbilityNameMap } from "../ability-names.js";

export function renderAbilitiesFile(
  manifest: Manifest,
  abilityNames: AbilityNameMap[],
): string {
  const typeImports = abilityNames
    .flatMap((a) =>
      a.hasNoInput
        ? [`${a.pascal}Output`]
        : [`${a.pascal}Input`, `${a.pascal}Output`],
    )
    .sort();

  const fns = abilityNames.map(renderFunction).join("\n\n");

  return `/**
 * AUTOGENERATED. Do not edit by hand.
 *
 * Source:      ${manifest.source}
 * Fetched at:  ${manifest.fetchedAt}
 * Manifest v:  ${manifest.schemaVersion}
 *
 * Regenerate with: \`jab generate <project-dir>\`
 */

/* eslint-disable */
/* tslint:disable */

import type { JabClient, JabRequestOptions } from "./client";
import type {
${typeImports.map((t) => `  ${t},`).join("\n")}
} from "./types";

${fns}
`;
}

function renderFunction(a: AbilityNameMap): string {
  // For taxonomy abilities whose wrapper key was derived from the plural
  // label (e.g. "Work Type" → wrapper `work_type`), surface the underlying
  // WP taxonomy slug so consumers know which key to use when reading
  // taxonomy data off CPT-list rows (rows are keyed by SLUG, not wrapper).
  const taxonomyTag = a.taxonomySlug
    ? `\n *\n * @taxonomy ${a.taxonomySlug} — CPT-list rows key per-post terms by this slug, which may differ from this ability's wrapper key.`
    : "";

  if (a.hasNoInput) {
    return `/**
 * Calls the \`${a.abilityName}\` ability.${taxonomyTag}
 */
export async function ${a.camel}(
  client: JabClient,
  requestOptions?: JabRequestOptions,
): Promise<${a.pascal}Output> {
  return client.callAbility<Record<string, never>, ${a.pascal}Output>(
    ${JSON.stringify(a.abilityName)},
    undefined,
    requestOptions,
  );
}`;
  }
  // Required-input abilities (e.g. by-slug) take input as a positional arg
  // with no default; optional-input abilities default to `{}` so callers
  // can omit it entirely when every property is optional.
  const inputParam = a.hasRequiredInput
    ? `input: ${a.pascal}Input`
    : `input: ${a.pascal}Input = {}`;
  return `/**
 * Calls the \`${a.abilityName}\` ability.${taxonomyTag}
 */
export async function ${a.camel}(
  client: JabClient,
  ${inputParam},
  requestOptions?: JabRequestOptions,
): Promise<${a.pascal}Output> {
  return client.callAbility<${a.pascal}Input, ${a.pascal}Output>(
    ${JSON.stringify(a.abilityName)},
    input,
    requestOptions,
  );
}`;
}
