/**
 * Emits `lib/sdk/abilities.ts` — one strongly-typed function per ability,
 * each delegating to a JabClient passed at call time.
 *
 * Shape:
 *   import { createClient } from "./client";
 *   const jab = createClient({ wpUrl: ..., user: ..., password: ... });
 *   const { posts } = await getPosts(jab, { numberposts: 5 });
 *
 * Passing the client explicitly (rather than a singleton) keeps the SDK
 * usable from Server Components, API routes, scripts, and tests without
 * stateful module-level setup. The user can wrap with their own helper
 * if they want a singleton style.
 */

import type { Manifest } from "../types/manifest.js";
import type { AbilityNameMap } from "../ability-names.js";

export function renderAbilitiesFile(
  manifest: Manifest,
  abilityNames: AbilityNameMap[],
): string {
  const typeImports = abilityNames
    .flatMap((a) =>
      a.hasNoInput
        ? [`${a.pascal}Output`]
        : [`${a.pascal}Input`, `${a.pascal}Output`],
    )
    .sort();

  const fns = abilityNames.map(renderFunction).join("\n\n");

  return `/**
 * AUTOGENERATED. Do not edit by hand.
 *
 * Source:      ${manifest.source}
 * Fetched at:  ${manifest.fetchedAt}
 * Manifest v:  ${manifest.schemaVersion}
 *
 * Regenerate with: \`jab generate <project-dir>\`
 */

/* eslint-disable */
/* tslint:disable */

import type { JabClient } from "./client";
import type {
${typeImports.map((t) => `  ${t},`).join("\n")}
} from "./types";

${fns}
`;
}

function renderFunction(a: AbilityNameMap): string {
  if (a.hasNoInput) {
    return `/** Calls the \`${a.abilityName}\` ability. */
export async function ${a.camel}(client: JabClient): Promise<${a.pascal}Output> {
  return client.callAbility<Record<string, never>, ${a.pascal}Output>(
    ${JSON.stringify(a.abilityName)},
  );
}`;
  }
  // Required-input abilities (e.g. by-slug) take input as a positional arg
  // with no default; optional-input abilities default to `{}` so callers
  // can omit it entirely when every property is optional.
  const inputParam = a.hasRequiredInput
    ? `input: ${a.pascal}Input`
    : `input: ${a.pascal}Input = {}`;
  return `/** Calls the \`${a.abilityName}\` ability. */
export async function ${a.camel}(
  client: JabClient,
  ${inputParam},
): Promise<${a.pascal}Output> {
  return client.callAbility<${a.pascal}Input, ${a.pascal}Output>(
    ${JSON.stringify(a.abilityName)},
    input,
  );
}`;
}
