/**
 * Emits `lib/sdk/client.ts` — a portable MCP HTTP client for the user's
 * Next.js / Node project. Zero runtime dependencies (Node 20+ native fetch).
 *
 * Implements the same Streamable HTTP handshake as the CLI's own client:
 * `initialize` → capture `Mcp-Session-Id` → `notifications/initialized`
 * → tool calls. Each `createClient()` returns a fresh handshake-on-first-call
 * instance, so callers can build it once at module init and reuse it.
 */

import type { Manifest } from "../types/manifest.js";

export function renderClientFile(manifest: Manifest): string {
  return `/**
 * AUTOGENERATED. Do not edit by hand.
 *
 * Source:      ${manifest.source}
 * Fetched at:  ${manifest.fetchedAt}
 * Manifest v:  ${manifest.schemaVersion}
 *
 * Regenerate with: \`jab generate <project-dir>\`
 */

/* eslint-disable */
/* tslint:disable */

const PROTOCOL_VERSION = "2025-06-18";
const CLIENT_NAME = "jab-sdk";
const CLIENT_VERSION = "0.1.0";

const DEFAULT_NAMESPACE = ${JSON.stringify(manifest.server.namespace)};
const DEFAULT_SERVER_ROUTE = ${JSON.stringify(manifest.server.route)};

export interface JabClientOptions {
  /** Full WP site URL, e.g. "https://example.com". No trailing slash required. */
  wpUrl: string;
  /** WordPress username. */
  user: string;
  /** WordPress Application Password. */
  password: string;
  /** Optional override of the MCP server REST namespace. */
  namespace?: string;
  /** Optional override of the MCP server REST route. */
  serverRoute?: string;
}

/**
 * Per-call fetch options forwarded to the underlying \`fetch()\`. Lets
 * consumers tag SDK requests for Next.js cache invalidation
 * (\`{ next: { tags: ["posts"] } }\`), set per-call \`revalidate\`, or pass
 * an \`AbortSignal\`. Headers and body are owned by the SDK and cannot
 * be overridden here.
 */
export type JabRequestOptions = Omit<RequestInit, "method" | "headers" | "body">;

export interface JabClient {
  /** Call any ability by full name (e.g. "jab/get-posts"). Strongly typed wrappers in abilities.ts are preferred. */
  callAbility<TInput extends object, TOutput>(
    abilityName: string,
    input?: TInput,
    requestOptions?: JabRequestOptions,
  ): Promise<TOutput>;
}

export class JabClientError extends Error {
  /** HTTP status code when the error originated from an HTTP-level failure.
   * Distinct from \`code\` which is set from JSON-RPC error codes. */
  public httpStatus?: number;
  constructor(
    message: string,
    public readonly cause?: unknown,
    public readonly code?: number,
  ) {
    super(message);
    this.name = "JabClientError";
  }
}

interface JsonRpcResponse<T> {
  jsonrpc: "2.0";
  id: number;
  result?: T;
  error?: { code: number; message: string; data?: unknown };
}

interface ToolCallResult<T> {
  content: Array<{ type: "text"; text: string }>;
  structuredContent?: { success: boolean; data: T; error?: string };
  isError: boolean;
}

/**
 * Build a strongly-typed-ish MCP client for the headless WP install.
 * Pair with the typed wrappers in abilities.ts for compile-time guarantees.
 */
export function createClient(opts: JabClientOptions): JabClient {
  const namespace = opts.namespace ?? DEFAULT_NAMESPACE;
  const serverRoute = opts.serverRoute ?? DEFAULT_SERVER_ROUTE;
  const baseUrl = opts.wpUrl.replace(/\\/+$/, "");
  const endpoint = \`\${baseUrl}/wp-json/\${namespace}/\${serverRoute}\`;
  const authHeader = \`Basic \${Buffer.from(\`\${opts.user}:\${opts.password}\`).toString("base64")}\`;

  let nextId = 1;
  let sessionId: string | null = null;
  let initialized = false;
  let initPromise: Promise<void> | undefined;

  async function post(
    body: string,
    includeSession: boolean,
    requestOptions?: JabRequestOptions,
  ): Promise<Response> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      Accept: "application/json, text/event-stream",
      Authorization: authHeader,
    };
    if (includeSession && sessionId) {
      headers["Mcp-Session-Id"] = sessionId;
    }
    try {
      // Spread requestOptions first so SDK-owned fields (method/headers/body)
      // always win — consumers can pass next/cache/signal/credentials, but
      // not override transport semantics.
      return await fetch(endpoint, { ...(requestOptions ?? {}), method: "POST", headers, body });
    } catch (err) {
      const cause = (err as { cause?: { code?: string } }).cause;
      if (
        cause?.code === "DEPTH_ZERO_SELF_SIGNED_CERT" ||
        cause?.code === "SELF_SIGNED_CERT_IN_CHAIN"
      ) {
        throw new JabClientError(
          \`TLS error connecting to \${endpoint}. Local dev with a self-signed cert? Set NODE_TLS_REJECT_UNAUTHORIZED=0 (dev only — never in CI/prod).\`,
          err,
        );
      }
      throw new JabClientError(\`Network error calling \${endpoint}: \${(err as Error).message}\`, err);
    }
  }

  async function parseRpcBody<T>(response: Response): Promise<JsonRpcResponse<T>> {
    const ct = response.headers.get("content-type")?.toLowerCase() ?? "";
    const text = await response.text();
    const json = ct.includes("text/event-stream") ? extractFirstSseDataLine(text) : text;
    if (!json) throw new JabClientError(\`Empty response body (Content-Type: \${ct || "unknown"})\`);
    try {
      return JSON.parse(json) as JsonRpcResponse<T>;
    } catch (err) {
      throw new JabClientError(\`Non-JSON response body (Content-Type: \${ct || "unknown"})\`, err);
    }
  }

  async function rpc<T>(
    method: string,
    params: Record<string, unknown> = {},
    requestOptions?: JabRequestOptions,
  ): Promise<T> {
    const id = nextId++;
    const response = await post(
      JSON.stringify({ jsonrpc: "2.0", id, method, params }),
      true,
      requestOptions,
    );
    if (!response.ok) {
      const text = await safeReadText(response);
      const httpErr = new JabClientError(\`HTTP \${response.status} from \${endpoint}\${text ? \`: \${text}\` : ""}\`, undefined, response.status);
      httpErr.httpStatus = response.status;
      throw httpErr;
    }
    const payload = await parseRpcBody<T>(response);
    if (payload.error) {
      throw new JabClientError(\`JSON-RPC error \${payload.error.code}: \${payload.error.message}\`, payload.error.data, payload.error.code);
    }
    if (payload.result === undefined) {
      throw new JabClientError("JSON-RPC response missing both result and error fields");
    }
    return payload.result;
  }

  async function ensureInitialized(): Promise<void> {
    if (initialized) return;
    // Singleton in-flight promise: concurrent callers (e.g. Promise.all over
    // two abilities on a cold client) must share one handshake. Without this,
    // each caller would POST initialize, the server would mint two sessions,
    // and the second notifications/initialized would race the first — leaving
    // one caller pointing at a session WP has already discarded.
    if (initPromise) return initPromise;
    initPromise = (async () => {
      const initId = nextId++;
      const initBody = JSON.stringify({
        jsonrpc: "2.0",
        id: initId,
        method: "initialize",
        params: {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: {},
          clientInfo: { name: CLIENT_NAME, version: CLIENT_VERSION },
        },
      });
      const response = await post(initBody, false);
      sessionId = response.headers.get("mcp-session-id");
      if (!sessionId) {
        throw new JabClientError("Server did not return Mcp-Session-Id header on initialize.");
      }
      if (!response.ok) {
        const text = await safeReadText(response);
        throw new JabClientError(\`initialize failed: HTTP \${response.status}\${text ? \`: \${text}\` : ""}\`, undefined, response.status);
      }
      const payload = await parseRpcBody<unknown>(response);
      if (payload.error) {
        throw new JabClientError(\`initialize JSON-RPC error \${payload.error.code}: \${payload.error.message}\`);
      }
      const notifyResponse = await post(
        JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }),
        true,
      );
      if (!notifyResponse.ok && notifyResponse.status !== 202) {
        const text = await safeReadText(notifyResponse);
        throw new JabClientError(\`notifications/initialized failed: HTTP \${notifyResponse.status}\${text ? \`: \${text}\` : ""}\`);
      }
      await notifyResponse.text().catch(() => undefined);
      initialized = true;
    })();
    try {
      await initPromise;
    } catch (err) {
      // Reset so the next call can retry from a clean slate.
      initPromise = undefined;
      sessionId = null;
      throw err;
    }
  }

  function resetSession(): void {
    initialized = false;
    initPromise = undefined;
    sessionId = null;
  }

  return {
    async callAbility<TInput extends object, TOutput>(
      abilityName: string,
      input?: TInput,
      requestOptions?: JabRequestOptions,
    ): Promise<TOutput> {
      const doCall = async (): Promise<TOutput> => {
        const result = await rpc<ToolCallResult<TOutput>>(
          "tools/call",
          {
            name: "mcp-adapter-execute-ability",
            arguments: {
              ability_name: abilityName,
              parameters: input ?? {},
            },
          },
          requestOptions,
        );
        if (result.isError) {
          const text = result.content?.[0]?.text ?? "(no error text)";
          throw new JabClientError(\`Ability \${abilityName} failed: \${text}\`);
        }
        const wrapped = result.structuredContent;
        if (!wrapped) {
          throw new JabClientError(\`Ability \${abilityName} returned no structuredContent\`);
        }
        if (!wrapped.success) {
          throw new JabClientError(\`Ability \${abilityName} reported failure: \${wrapped.error ?? "(no error)"}\`);
        }
        return wrapped.data;
      };
      await ensureInitialized();
      const sessionAtCall = sessionId;
      try {
        return await doCall();
      } catch (err) {
        // mcp-adapter invalidated the session (HTTP 404 per the MCP spec's
        // session management). Module-scoped singletons (lib/sdk via proxy)
        // otherwise stay broken until the serverless instance recycles —
        // re-initialize once and retry. CAS guard: under concurrent 404s only
        // the FIRST catcher rotates the session; the rest join the in-flight
        // handshake instead of clobbering it (dual-handshake crosstalk).
        if (err instanceof JabClientError && err.httpStatus === 404) {
          if (sessionId === sessionAtCall) {
            resetSession();
          }
          await ensureInitialized();
          try {
            return await doCall();
          } catch (retryErr) {
            if (retryErr instanceof JabClientError && retryErr.httpStatus === 404) {
              const terminalErr = new JabClientError(
                \`Ability \${abilityName}: MCP session could not be re-established (HTTP 404 after re-initialize). Verify the JAB plugin and wordpress/mcp-adapter are active at \${endpoint}.\`,
                retryErr,
                404,
              );
              terminalErr.httpStatus = 404;
              throw terminalErr;
            }
            throw retryErr;
          }
        }
        throw err;
      }
    },
  };
}

function extractFirstSseDataLine(text: string): string | null {
  for (const line of text.split(/\\r?\\n/)) {
    if (line.startsWith("data:")) return line.slice(5).trim();
  }
  return null;
}

async function safeReadText(response: Response): Promise<string> {
  try {
    const text = await response.text();
    return text.length > 500 ? \`\${text.slice(0, 500)}…\` : text;
  } catch {
    return "";
  }
}
`;
}
