/**
 * Emits `lib/sdk/index.ts` — a barrel that re-exports the public surface
 * of the generated SDK.
 *
 * Static; nothing about it depends on the manifest.
 */

export function renderIndexFile(): string {
  return `/**
 * AUTOGENERATED. Do not edit by hand.
 *
 * Public surface of the Jab headless SDK.
 *
 *   import { createClient, getPosts, getBeers } from "@/lib/sdk";
 *
 * Regenerate with: \`jab generate <project-dir>\`
 */

/* eslint-disable */
/* tslint:disable */

export * from "./client";
export * from "./abilities";
export type * from "./types";
`;
}
